### PR TITLE
feat: Add Vercel Serverless Hosting Support

### PR DESCRIPTION
**Pull request by GabrielTK**
This adds a `VercelServer` class, which allows the bot to be hosted on [Vercel](https://vercel.com/) - a free hosting platform for serverless projects strongly integrated with Git.
A working code example is [available here](https://github.com/GabrielTK/VercelSlashCreate), is currently being hosted via Vercel and can be tested [with this invite link](https://discord.com/oauth2/authorize?client_id=619935227737014333&scope=bot%20applications.commands&permissions=8) (NOTE: The invite link by default includes Administrator permissions, but that should not change anything. If you feel uncomfortable with testing it this way, just change the `permissions` bit on the URL.

### CODE REVIEW

**Comment by Snazzah** [comment]
Could you add documentation in `docs` on how to set it up via Vercel?

**Comment by GabrielTK** [comment]
Sure thing, I’d be more than happy to! I believe it might be quite necessary as well, since it’s setup is quite exquisite, with the need to create an API file - I just really forgot to.

**Comment by GabrielTK** [comment]
@Snazzah, I added some Docs explaining how to implement it. I'm not a native speaker, so please let me know if it is unclear.

**Comment by Snazzah** [comment]
@GabrielTK Could you explain in the docs how to deploy it in Vercel? Like what environment keys to use, what the interaction URL should be, etc.

**Comment by GabrielTK** [comment]
Actually, I would like to ask you for your opinion on something: Vercel tends to restart the runtime after an HTTP response has been sent, thus clearing all variables - wouldn’t that create an issue with message components such as selects?

**Comment by Snazzah** [comment]
Yes, uou wouldn't be able to use `ctx.registerComponent`.

**Comment by Snazzah** [comment]
Merging this now, I'll work on the documentation and making sure it works well on Vercel.

**Pull request merged**
